### ISSUE TITLE
Setting switch state requires multiple attempts

### ISSUE THREAD

**Issue by giacomo270197** [crownstone/bluenet-python-lib#4]
Setting the switch state of a Crownstone often throws a `bluepy.btle.BTLEException`:
The complete output of the following script:

```
import sys
import connect_to_stone
from BluenetLib.BLE import BluenetBle

ble = BluenetBle(hciIndex=0)
ble.loadSettingsFromFile("keys.json")
connect_to_stone.connect_to_stone(ble, sys.argv[1])
ble.control.setSwitchState(int(sys.argv[2]))
ble.disconnect()
ble.shutDown()
```

is the following:

```
Connecting...
Traceback (most recent call last):
  File "switch_stone.py", line 7, in <module>
    connect_to_stone.connect_to_stone(ble, sys.argv[1])
  File "/home/giacomo.local/Crownstone/connect_to_stone.py", line 7, in connect_to_stone
    module.connect(address)
  File "/usr/local/lib/python3.6/site-packages/BluenetLib-0.5.4-py3.6.egg/BluenetLib/lib/core/BluetoothCore.py", line 49, in connect
  File "/usr/local/lib/python3.6/site-packages/BluenetLib-0.5.4-py3.6.egg/BluenetLib/lib/core/bluenet_modules/BleHandler.py", line 54, in connect
  File "/usr/local/lib/python3.6/site-packages/bluepy-1.1.4-py3.6.egg/bluepy/btle.py", line 408, in connect
    self._connect(addr, addrType, iface)
  File "/usr/local/lib/python3.6/site-packages/bluepy-1.1.4-py3.6.egg/bluepy/btle.py", line 402, in _connect
    "Failed to connect to peripheral %s, addr type: %s" % (addr, addrType))
bluepy.btle.BTLEException: Failed to connect to peripheral f4:c1:95:40:7d:2c, addr type: random
^CException ignored in: <module 'threading' from '/usr/lib64/python3.6/threading.py'>
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/lib64/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib64/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
```

Simply running the script several times eventually ends up in a success to turn the stone on/off.
Is there a reason why this could happen? (the bluetooth command is sent by a laptop, not more than 20cm from the stone)

**Comment by mrquincle** [comment]
Hi, I can confirm this error. For now, please try multiple times. :-) It might be quite deep in the python BLE handling, so we will need to look into it for a while. If you can find where it fails, you will do us a huge favor!
